version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"           
    rebase-strategy: "auto" 
    target-branch: "stable"
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        patterns:
          - "*"