version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"           
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "*" 
    rebase-strategy: "auto" 
    groups:
      npm-dependencies:
        patterns:
          - "*"