services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./api/data:/usr/src/app/api/data
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8080:80"
    depends_on:
      - api