services:
  api:
    image: ghcr.io/shockedplot7560/wishnest/api:latest
    volumes:
      - ./api/data:/usr/src/app/api/data
    ports:
      - "3000:3000"

  front:
    image: ghcr.io/shockedplot7560/wishnest/front:latest
    ports:
      - "80:80"
    depends_on:
      - api