services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8080:8080"
    depends_on:
      - api